endpoints:
  - name: localhost
    url: "http://localhost:8080"
    interval: 30s
    conditions:
      - "[STATUS] == 200"

  - name: google
    url: "https://www.google.com"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[BODY] == pat(*<title>Google</title>*)"

  - name: bleacherreport
    url: "https://bleacherreport.com/nfl"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[BODY] == pat(*<title>Bleacher Report</title>*)"
