name: build & push docker image to ecr

on:
  push:
    branches:
      - master
    paths:
      - 'application/**'
      - '.github/workflows/**'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository 
        uses: actions/checkout@v4

      - name: Configure AWS credentials w/ OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_APP_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: login to ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build docker image
        run: docker build -t gatus:latest ./application

      - name: security test image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: gatus:latest
          format: table
          version: v0.69.2
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
      
      - name: test locally
        run: |
          docker run -d --rm --name gatus-app -p 8080:8080 gatus:latest
          sleep 10
          if [ "$(docker ps -q -f name=gatus-app)" ]; then
            echo "Up & running ✅"
          else
            echo "Failed 🚨" && exit 1
          fi
          if curl --fail http://localhost:8080 > /dev/null; then
            echo "Responding well 🎉"
          else
            echo "I can't hear you buddy 🚨" && exit 1
          fi
          docker stop gatus-app

      - name: tag & push docker image to ecr
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        run: |
          docker tag gatus:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest