name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Safety Check: Type "destroy" to confirm teardown'
        required: true
        type: string

concurrency:
  group: "deploy-infrastructure" 
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  WORKING_DIR: ./terraform/environment/dev

jobs:
  teardown-infrastructure:
    runs-on: ubuntu-latest
    
    steps:
      - name: safety lock
        run: |
          if [ "${{ github.event.inputs.confirm_destroy }}" != "destroy" ]; then
            echo "ERROR ✋🏽: You did not type 'destroy'. Infrastructure is safe."
            exit 1
          fi
          echo "Teardown confirmed. Proceeding...⏳"

      - name: checkout repository 
        uses: actions/checkout@v4

      - name: configure AWS credentials w/ OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_INFRA_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: terraform setup
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.7"

      - name: terraform init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init -input=false

      - name: 🗑️ terraform destroy
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform destroy --auto-approve -input=false -var="container_image=teardown-placeholder"

      - name: final status dashboard
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Teardown Successful ✅" >> $GITHUB_STEP_SUMMARY
            echo "All AWS resources have been cleanly deleted" >> $GITHUB_STEP_SUMMARY
          else
            echo "Teardown Failed!" >> $GITHUB_STEP_SUMMARY
            echo "Check the Terraform logs above. Some resources might still be running in AWS which may require manual deletion." >> $GITHUB_STEP_SUMMARY
          fi